controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

delete_account:
    path: /delete-account
    controller: App\Controller\ProfileController::deleteAccount
    methods: [POST]